version: "3.8"
services:
  deno-app:
    build: .
    # Use named volume for persistent data
    volumes:
      - deno_data:/app/data
    ports:
      - "8001:8000"
    environment:
      - DENO_ENV=production

volumes:
  deno_data:
    name: "deno_data"
