version: "3.8"
services:
  deno-app:
    build: .
    volumes:
      - .:/deno-dir
    ports:
      - "8001:8000"
    environment:
      - DENO_ENV=production
    command: ["deno", "run", "-A", "main.ts"]
